export const ChainId = {
  MAINNET: 1,
  ROPSTEN: 3,
  MATIC: 137,
  MUMBAI: 80001,
};

export const NETWORKS_INFO = {
  [ChainId.MAINNET]: {
    chainId: ChainId.MAINNET,
    name: 'Ethereum',
    urlKey: 'ethereum',
    dmmSwapUrl: 'https://kyberswap.com/',
    subgraphName: 'dynamic-amm/dynamic-amm',
    balancerSubgraphUrl: 'https://api.thegraph.com/subgraphs/name/verified-network/balancer',
    subgraphUrls: ['https://api.thegraph.com/subgraphs/name/kybernetwork/kyberswap-exchange-ethereum'],
    subgraphBlockUrl: 'https://api.thegraph.com/subgraphs/name/dynamic-amm/ethereum-blocks-ethereum',
    etherscanUrl: 'https://etherscan.io',
    kncAddress: '0xdeFA4e8a7bcBA345F687a2f1456F5Edd9CE97202',
    wethAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
    defaultStartTime: 1620201600,
    nativeTokenSymbol: 'ETH',
    nativeTokenWrappedName: 'Ether (Wrapped)',
    etherscanLinkText: 'Etherscan',
    tokensListUrl: 'https://raw.githubusercontent.com/KyberNetwork/ks-assets/main/tokenLists/ethereum.tokenlist.json',
    factoryAddress: '0x833e4083B7ae46CeA85695c4f7ed25CDAd8886dE',
  },
  [ChainId.ROPSTEN]: {
    chainId: ChainId.ROPSTEN,
    name: 'Ropsten',
    urlKey: 'ropsten',
    dmmSwapUrl: 'https://dev-dmm.knstats.com/#/',
    subgraphName: 'piavgh/dmm-exchange-ropsten',
    subgraphUrls: ['https://api.thegraph.com/subgraphs/name/viet-nv/kyberswap-classic-ropsten'],
    subgraphBlockUrl: 'https://api.thegraph.com/subgraphs/name/edwardevans094/ropsten-blocks',
    etherscanUrl: 'https://ropsten.etherscan.io',
    kncAddress: '0x8B4DDF9F13f382aff76D262F6C8C50E6d7961b94',
    wethAddress: '0xc778417E063141139Fce010982780140Aa0cD5Ab',
    defaultStartTime: 1620201600,
    nativeTokenSymbol: 'ETH',
    nativeTokenWrappedName: 'Ether (Wrapped)',
    etherscanLinkText: 'Etherscan',
    tokensListUrl: 'https://raw.githubusercontent.com/KyberNetwork/ks-assets/main/tokenLists/ropsten.tokenlist.json',
    factoryAddress: '0x0639542a5cd99bd5f4e85f58cb1f61d8fbe32de9',
  },
  [ChainId.MATIC]: {
    chainId: ChainId.MATIC,
    name: 'Polygon',
    urlKey: 'polygon',
    dmmSwapUrl: 'https://kyberswap.com/',
    subgraphName: 'dynamic-amm/dmm-exchange-matic',
    subgraphUrls: [
      'https://api.thegraph.com/subgraphs/name/kybernetwork/kyberswap-exchange-polygon',
      'https://polygon-subgraph.dmm.exchange/subgraphs/name/dynamic-amm/dmm-exchange-matic',
    ],
    subgraphBlockUrl: 'https://api.thegraph.com/subgraphs/name/dynamic-amm/ethereum-blocks-polygon',
    etherscanUrl: 'https://polygonscan.com',
    kncAddress: '0x1C954E8fe737F99f68Fa1CCda3e51ebDB291948C',
    wethAddress: '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270',
    defaultStartTime: 1625097600,
    nativeTokenSymbol: 'MATIC',
    nativeTokenWrappedName: 'Matic (Wrapped)',
    etherscanLinkText: 'Polygonscan',
    tokensListUrl: 'https://raw.githubusercontent.com/KyberNetwork/ks-assets/main/tokenLists/matic.tokenlist.json',
  },
  [ChainId.MUMBAI]: {
    chainId: ChainId.MUMBAI,
    name: 'Mumbai',
    urlKey: 'mumbai',
    dmmSwapUrl: 'https://dev-dmm.knstats.com/#/',
    subgraphName: 'piavgh/dmm-exchange-mumbai',
    subgraphUrls: ['https://api.thegraph.com/subgraphs/name/piavgh/dmm-exchange-mumbai'],
    subgraphBlockUrl: 'https://api.thegraph.com/subgraphs/name/piavgh/mumbai-blocks',
    etherscanUrl: 'https://mumbai.polygonscan.com',
    kncAddress: '0xFD1f9381Cb641Dc76Fe8087dbcf8ea84a2c77cbE',
    wethAddress: '0x9c3c9283d3e44854697cd22d3faa240cfb032889',
    defaultStartTime: 1625097600,
    nativeTokenSymbol: 'MATIC',
    nativeTokenWrappedName: 'Matic (Wrapped)',
    etherscanLinkText: 'Polygonscan',
    tokensListUrl: 'https://raw.githubusercontent.com/KyberNetwork/ks-assets/main/tokenLists/mumbai.tokenlist.json',
  },
};
